<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>bfd55b6c-18d5-4934-8514-f27388c23f90</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
        <PackageReference Include="Microsoft.ML" Version="5.0.0" />
        <PackageReference Include="MongoDB.Driver" Version="3.10.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    </ItemGroup>
    <ItemGroup>
        <None Update="model.zip">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
   

</Project>
